---
title: "Gov 50 Final Project"
author: "Jenny Lu"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I'm interested in exploring data related to cities in the United States -- specifically, items such as public transport systems, land use, green space, and walkability. I'd like to explore the relationship between factors like demographics or income and the way in which people interact with the space around them in an urban environment.


## Proposal

How has public transport been impacted by the COVID-19 pandemic? More specifically, which form of public transport has been hit the hardest? I'm interested in studying the extent to which ridership has/has not recovered since the pandemic. In this study, I plan to examine data from the New York City Metropolitan Transportation Authority (MTA), containing statistics on ridership and the corresponding proportion of pre-pandemic ridership levels for each of the forms of public transport offered under the MTA in the greater New York City metropolitan area. I hypothesize that the Subway form of public transport suffered the largest impact on ridership from the pandemic, due to it having the highest ridership levels relative to all other forms of public transport, as well as the unavoidable proximity to others its riders must endure, and as a consequence, is likely viewed to be of highest-risk. The explanatory variable of interest is the date and time of each measurement -- data on ridership has been collected daily since March 1st, 2020. My outcome variable of interest is the "% of Comparable Pre-Pandemic Day" values for each of the forms of public transport. This is found by measuring daily ridership, then estimating as a percentage of ridership on that particular form of public transport on an equivalent day prior to the COVID-19 pandemic. Observing that Subways had a larger decline in "% of Comparable Pre-Pandemic Day" values than other forms of public transport would provide support for my hypothesis. However, observing that forms of public transport, such as Buses or other light-rail systems, had larger declines in "% of Comparable Pre-Pandemic Day" values than that of Subways would disprove my hypothesis.